ui/packages/models/src/ui.model.ts
ui/packages/services/src/connector/connector.service.ts
ui/packages/ui/src/app/pages/connectors/ConnectorIcon.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorsPage.tsx
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/SelectConnectorTypeComponent.tsx
ui/packages/ui/src/app/shared/Utils.ts

I missed that there was an id on the ConnectorType in my initial commit.  Better to identify ConnectorType by the id vs the longer classname - so I added the id to the model, then converted the usages.  Also added some comments in ConnectorService

use connector id to identify

---

ui/packages/models/src/ui.model.ts
ui/packages/services/src/connector/connector.service.ts
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConfigureConnectorTypeComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/FiltersStepComponent.tsx
ui/packages/ui/src/app/shared/Utils.ts

Some initial work on supplying the correct subset of ConnectorProperties to the relevant pages.
- added ConnectorConfiguration model.  This is the object that will be passed to the 'createConnector' service
- added optional 'category' attribute to ConnectorProperty (this is not used yet)
- added createConnector function to the service, but it's commented out/not used yet.
- the FiltersStepComponent/ConfigureConnectorTypeComponent have properties for setting the relevant ConnectorProperties.
- added functions in Utils which group the property definitions by 'category' for supplying to the components.  This will change once the backend(hopefully) is able to supply category info.
- Each component has 'onSaveProperties' and 'onValidateProperties'.  The config property name-value pairs can …

Supply ConnectorProperties to components

---

ui/packages/services/src/connector/connector.service.ts
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConfigureConnectorTypeComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/FiltersStepComponent.tsx
ui/packages/ui/src/app/shared/CategoryUtil.ts
ui/packages/ui/src/app/shared/Utils.ts
ui/packages/ui/src/app/shared/index.ts

Made some adjustments to categorizing properties, and also made some changes to maintaining of the property values.  Did preliminary wiring of validation/save from the components.
- The assignment of property category was moved into CategoryUtil.  The optional category attribute is set on ConnectorProperty based on the property name.  Hopefully we can just remove this if the backend service can do the categorization.
- In CreateConnectorPage, now maintaining a map of the property values for each category separately.  These are then supplied to the appropriate wizard component for init of its forms.  Seemed easier to maintain this way, then upon finish merge the category maps to create the ConnectorConfiguration for submittal to the createConnector service.
- Removed the 'onSaveProperties' …

Using property optional category, connecting test validation

---

ui/packages/models/src/ui.model.ts
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConfigureConnectorTypeForm.tsx
ui/packages/ui/src/app/shared/CategoryUtil.ts

Adds an optional 'orderInCategory' attribute to the ConnectorProperty UI model, to assist in correct ordering of properties within a category/sub-group.
- An extra step was added in CategoryUtil which iterates the properties, assigning ordering to the properties within each category.
- The orderInCategory attribute is then utilized in ConfigureConnectorTypeForm to sort the property definitions
This is still very much a work-in-progress.  It is expected that the service layer will supply the category/group info - when that is ready, the CategoryUtil assigned categories will be removed and the ordering reworked.  In a similar way, we could also customize additional layout info for each property within the UI if needed (for example maybe row / column positioning or sizing).

Adding optional orderInCategory attribute to UI property model

---

ui/packages/models/src/ui.model.ts
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConfigureConnectorTypeForm.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/index.ts
ui/packages/ui/src/app/pages/createConnector/connectorSteps/runtimeOptions/RuntimeOptionsComponent.css
ui/packages/ui/src/app/pages/createConnector/connectorSteps/runtimeOptions/RuntimeOptionsComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/runtimeOptions/RuntimeOptionsForm.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/runtimeOptions/index.tsx
ui/packages/ui/src/app/shared/CategoryUtil.ts
ui/packages/ui/src/app/shared/Utils.ts

Added a component for the final wizard step - Runtime Options.  The properties are grouped into 'Engine properties' and 'Heartbeat properties' per the current mockup.
- Reworked the categories for Data Options and Runtime Options to better match the design doc.
- added SSL properties and a few other missing properties.  SSL will not be displayed initially - it's just there for completeness
- Added the RuntimeOptionsComponent and RuntimeOptionsForm.  Validation still needs to be hooked up
Much of this will require more rework whenever the service is in place which provides additional property metadata (eg category, ordering, etc).

Adding Runtime options step to wizard

---

backend/src/main/java/io/debezium/configserver/model/AdditionalPropertyMetadata.java
backend/src/main/java/io/debezium/configserver/model/ConnectorProperty.java
backend/src/main/java/io/debezium/configserver/rest/ConnectorResource.java
backend/src/main/java/io/debezium/configserver/service/ConnectorIntegrator.java
backend/src/main/java/io/debezium/configserver/service/ConnectorIntegratorBase.java
backend/src/main/java/io/debezium/configserver/service/postgres/PostgresConnectorIntegrator.java
backend/src/main/java/io/debezium/configserver/service/temp/MongoDbConnectorIntegrator.java
backend/src/main/java/io/debezium/configserver/service/temp/MySqlConnectorIntegrator.java
backend/src/main/java/io/debezium/configserver/service/temp/SqlServerConnectorIntegrator.java
backend/src/test/java/io/debezium/configserver/ConnectorResourceIT.java
backend/src/test/java/io/debezium/configserver/CreatePostgresConnectorIT.java
backend/src/test/java/io/debezium/configserver/MultipleKafkaConnectClustersIT.java
backend/src/test/java/io/debezium/configserver/NativeValidatePostgresConnectionIT.java
backend/src/test/java/io/debezium/configserver/NativeValidatePostgresFiltersIT.java
backend/src/test/java/io/debezium/configserver/ValidatePostgresConnectionIT.java
backend/src/test/java/io/debezium/configserver/ValidatePostgresFiltersIT.java
backend/src/test/java/io/debezium/configserver/util/Infrastructure.java
backend/src/test/java/io/debezium/testing/testcontainers/ConnectorConfigurationTestingHelper.java

+ Add additional property metadata to /connector-types endpoint
+ Add additional /connector-types/{id} endpoint to only fetch metadata for a specific connector
+ Add and extend unit tests
closes #50 
FYI @gunnarmorling

Add additional property metadata to /connector-types endpoint

---

ui/packages/models/src/ui.model.ts
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConfigureConnectorTypeForm.css
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConfigureConnectorTypeForm.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/dataOptions/DataOptionsForm.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/runtimeOptions/RuntimeOptionsForm.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/shared/FormCheckboxComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/shared/FormComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/shared/FormSelectComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/shared/FormSwitchComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/shared/index.tsx
ui/packages/ui/src/app/shared/CategoryUtil.ts
ui/packages/ui/src/app/shared/Utils.ts

Additional work to adapt to the service additions and refine properties 
- updated the ConnectorProperty model: category and isMandatory are no longer optional - they are supplied by the service.  Added 'allowedValues' attribute.  Aligned the category names to match those being supplied by the service.
- CategoryUtils - Removed specification of category and required since they are now supplied by the service.  Added some missing properties and fixed some ordering.
- ConfigureConnectorTypeForm - did some reorganization to put the properties into titled areas.  Also added some logic which hides the publication group if 'plugin' != Pgoutput.
- Created a generic 'FormComponent' - this component handles the logic to determine which specific form element is suitable for the supplied …

Refining properties and adapting to service

---

ui/packages/models/src/ui.model.ts
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConfigureConnectorTypeForm.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/shared/FormCheckboxComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/shared/FormComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/shared/FormInputComponent.tsx

Address a couple issues with form components
- allowedValues and defaultValue are optional in the model
- ConfigureConnectorTypeForm - the value is included for validation if a property has no default, or if the form value is different than the default
- other adjustments to form component for init

Adjustments to form components

---

backend/src/main/java/io/debezium/configserver/service/ConnectorIntegratorBase.java
backend/src/test/java/io/debezium/configserver/ValidatePostgresFiltersIT.java

Excluding invisible fields lead to that other invisible fields are not validated at all (e.g. SCHEMA_EXLUDE_LIST / SCHEMA_BLACKLIST).
they are invisible and should not be ignored. Had to introduce a dirty string comparison until we have validation result instances on Debezium side and we can figure out if a validation error is a WARNing or ERRor.

* fixed dependents validation again:

---

ui/packages/models/src/ui.model.ts
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConfigureConnectorTypeComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/dataOptions/DataOptionsComponent.css
ui/packages/ui/src/app/pages/createConnector/connectorSteps/dataOptions/DataOptionsComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/runtimeOptions/RuntimeOptionsComponent.tsx
ui/packages/ui/src/app/shared/Utils.ts

- Reorganized Data Options step to better match the mockups
- Reorganized Runtime Options step - put property groups into accordions, to be consistent with other steps
- added connector name property into the basic properties.  The connection name is displayed at the top of the property configuration page.  Now passing the entered connector name upon create of the connector.
- other minor wording changes and clean up

reorganize data options, add connector name input

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConfigureConnectorTypeComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConnectorTypeStepComponent.css
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConnectorTypeStepComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/dataOptions/DataOptionsComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/runtimeOptions/RuntimeOptionsComponent.tsx
ui/packages/ui/src/app/shared/Utils.ts

- Improved display of errors coming from backend service when a form is validated.
- Fixed connector type cards have different heights
- Fixed step 4 and 5 not sending data to backend and moved Format Property Definitions function to Utils.

Send properties to backend

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/shared/Utils.ts

Added Util function which minimizes the property values being set to the backend for validation / connector creation.  This essentially is now relying on the backend to use the appropriate default values for the properties.

Minimizing property values sent to backend for validation / creation

---

ui/packages/models/src/ui.model.ts
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConfigureConnectorTypeComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/FiltersStepComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/dataOptions/DataOptionsComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/runtimeOptions/RuntimeOptionsComponent.tsx
ui/packages/ui/src/app/shared/Utils.ts

Improved layout of properties by shortening some input components similar to mockup layouts
- added optional attribute 'gridWidth' to ConnectorProperty
- added function in Utils to set the gridWidth attribute on incoming properties
- wrapped the Accordion components to shorten overall form input widths to 75% of available space
- property gridWidth attributes are then used in the form grids to display appropriate width elements
- also improved the filter popover text and added a link to regex information

Improvements to form layouts

---

ui/packages/models/src/ui.model.ts
ui/packages/services/src/connector/connector.service.ts
ui/packages/ui/src/app/pages/connectors/ConnectorListItem.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorStatus.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorsPage.tsx
ui/packages/ui/src/app/shared/Utils.ts

Some initial work to adapt the UI to the actual connector list from the backend service
- updated Connector model object in the UI
- created function in connector service to get the connector list
- adapted ConnectorListItem for display of the connector attributes
- created ConnectorStatus component for display of the connector status as a label with varying colors
- included the fetch in the ConnectorsPage, but it is still commented out until the backend code is merged.
- 'taskStates' just temp data for now - it will need to be hooked up.

Adapt to connector list response from service

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx

Adds details message to the error alert - if there is a problem creating the connector.  If no message, then a generic message is added.

Add detail info to error alert

---

ui/packages/ui/src/app/Layout/AppLayout.tsx
ui/packages/ui/src/app/Layout/AppLayoutContext.tsx
ui/packages/ui/src/app/Layout/appHeader.tsx
ui/packages/ui/src/app/components/KafkaConnectCluster.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorListItem.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorsPage.tsx

Additional work on the connector list page and connector items
- modify kafka connect cluster component to pass the clusterId on change.  This allows the ConnectorsPage to get the id directly from the context instead of fetching the connectors again to determine the id.
- remove call from ConnectorsPage to get clusters - no longer needed
- fix the fetch of the connectors list
- passing actual task state to ConnectorListItem (was hardcoded)
- adapt ConnectorListItem to recognize alternate PostgreSQL type name.

Connector list page work for fetch of connectors list

---

backend/src/main/java/io/debezium/configserver/rest/FrontendConfigResource.java
ui/packages/services/src/config/config.service.ts
ui/packages/ui/src/index.html

Create/Generate `config.js` inside `build` or `dist` folder with the following code snippet and change `url `accordingly.
```
window.DEFAULT_CONFIG = {
artifacts: {
type: "rest",
url: "http://localhost:8080/api/"
},
features: {
readOnly: false
},
mode: "dev",
ui: {
contextPath: null,
url: "http://localhost:8888/"
}
};
```
closes #168

Making backend base URL configurable

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/FiltersStepComponent.tsx

- address brief flashing of alert by adding validationInProgress state.  If validation is in progress, a spinner is shown
- address similar issue on filters page - a spinner is shown on the lower panel when loading
- address problem with deselect of connector type.  Not resetting properties if connectorType is deselected.  Also disabling next button if no type is selected
- click finish on steps 2-5 will now go to the final review step instead of create connector.  Create only happens from the review step now.

Fix a few UI issues

---

ui/config/config.js
ui/config/version.js
ui/packages/services/src/config/config.service.ts
ui/packages/ui/src/index.html
ui/packages/ui/webpack.dev.js

1. Removing `DEFAULT_CONFIG` from services config.
2. Using `CopyWebpackPlugin` to copy from `/ui/config/config.js` to `dist` 
3. Reading config from global variable (DebeziumUiConfig) directly

Removing default config from services

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx

Redirecting create connector page to `/app` if connector names from location state is undefined

Fixing undefined Connector Names from location state 

---

ui/packages/models/src/ui.model.ts
ui/packages/ui/src/app/components/formHelpers/FormComponent.tsx
ui/packages/ui/src/app/components/formHelpers/FormSwitchComponent.tsx
ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx
ui/packages/ui/src/app/shared/Utils.ts

Addresses issue #220 - UX request to use toggle switch for a couple properties
- add 'BOOLEAN-SWITCH' to ui model to distinguish toggle switch props
- update FormComponent to check for BOOLEAN-SWITCH type
- update Utils.getFormattedProperties to handle the switch properties

Utilizing switch component for some properties

---

ui/packages/models/src/ui.model.ts
ui/packages/ui/src/app/components/formHelpers/FormCheckboxComponent.css
ui/packages/ui/src/app/components/formHelpers/FormCheckboxComponent.tsx
ui/packages/ui/src/app/components/formHelpers/FormComponent.tsx
ui/packages/ui/src/app/components/formHelpers/FormDurationComponent.tsx
ui/packages/ui/src/app/components/formHelpers/FormInputComponent.tsx
ui/packages/ui/src/app/components/formHelpers/FormSwitchComponent.tsx
ui/packages/ui/src/app/components/formHelpers/index.tsx
ui/packages/ui/src/app/shared/Utils.ts

Adding a duration component, Issue #126 - and a couple other component improvements.  Some of the properties which utilize the duration component will need to have their titles and descriptions adjusted - I will log a follow-up request for that
- added FormDurationComponent, which allows the user to enter duration values in different units.  Regardless of the selected units, the value is always stored as milliseconds and provided as ms to the backend.
- added a new ConnectorProperty type 'DURATION' to the model and now designating the duration properties in Utils.getFormattedProperties.
Screenshot example of duration component:
- Added HelpInfoIcon to the checkbox and switch components, for display of the property descriptions, similar to other properties
- added new ConnectorProperty …

Adding duration component

---

ui/packages/ui/src/app/components/formHelpers/HelpInfoIcon.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorStatus.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorTask.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorsTableComponent.tsx
ui/packages/ui/src/app/shared/Utils.ts

- remove units from duration form component titles.  The user can select different units, so the titles were confusing
- remove tooltips from ConnectorStatus in the table - the tooltip didn't provide any additional info
- in ConnectorTask, changed tooltip to popover.  The popover icon will only show up if there are additional errors to display.
- added aria-label to the HelpInfoIcon.  Should help with accessibility for the help popovers

Fix duration titles, rework table tooltips

---

ui/packages/ui/src/app/components/formHelpers/HelpInfoIcon.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorTask.css
ui/packages/ui/src/app/pages/connectors/ConnectorTask.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorsTableComponent.tsx

Changes to allow better formatting of the task errors
- allow element in HelpInfoIcon
- changes in ConnectorTask to better format the errors

Adjustments to TaskStatus

---

ui/packages/models/src/ui.model.ts
ui/packages/ui/src/app/components/formHelpers/FormComponent.tsx
ui/packages/ui/src/app/components/formHelpers/FormMaskHashSaltComponent.css
ui/packages/ui/src/app/components/formHelpers/FormMaskHashSaltComponent.tsx
ui/packages/ui/src/app/components/formHelpers/FormMaskOrTruncateComponent.tsx
ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx
ui/packages/ui/src/app/shared/Utils.ts

Comments form @mdrillin original pr
> Adds UI component to handle the hash-salt masking property.
> 
> using same strategy for the value as the column truncation and masking component, but 3 parts are combined instead of 2. Different delimiters are used to separate the different segments
> added 'COLUMN_MASK_HASH_SALT' type in the model, so that the property can be distinguished from others
> made a couple of minor naming changes

Mask hash salt component

---

ui/packages/ui/src/app/components/formHelpers/FormComponent.tsx
ui/packages/ui/src/app/components/formHelpers/FormMaskHashSaltComponent.css
ui/packages/ui/src/app/components/formHelpers/FormMaskHashSaltComponent.tsx
ui/packages/ui/src/app/components/formHelpers/FormMaskOrTruncateComponent.css
ui/packages/ui/src/app/components/formHelpers/MaskHashSaltItem.css
ui/packages/ui/src/app/components/formHelpers/MaskHashSaltItem.tsx
ui/packages/ui/src/app/shared/Utils.ts

This adds the multi-row capability to the 'MaskHashSalt' component.  Took a similar approach as with the other multi-row property, breaking the item out into a separate component.

Adds multiple hash-salt property capability

---

ui/packages/ui/src/app/pages/createConnector/connectorSteps/TableSelectionStep.tsx

Fix for removing the spinner in case of API error in the table selection step.

Fixed the alert spinner in table selection step

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx
ui/packages/ui/src/app/shared/Utils.ts

Fix for issue #271 - next button was remaining enabled after connector type change
- Reset some states after connectorType change, to re-init
- combining 2 ConfirmationDialog usages into 1
- Utils fix to ensure propNames are properly matched (was losing formatting after form validations due to formik name adjustments)

Fix issue with wizard next button

---

ui/packages/ui/src/app/app.tsx
ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx

Fixed issue https://github.com/debezium/debezium-ui-poc/issues/258
Updated the browser back button confirm implementation code, now using `<Prompt>` available in react-router to check the back event and rendering custom UI.

Updated the browser back button confirm handling by using prompt

---

ui/packages/services/src/connector/connector.service.ts
ui/packages/ui/src/app/i18n/locales/translations.en.json
ui/packages/ui/src/app/i18n/locales/translations.it.json
ui/packages/ui/src/app/pages/connectors/ConnectorsTableComponent.tsx

- Added connector service mock for Pause / Resume / Restart service call.
- Using `httpPost` method as of now, will replace according to backend implementation

Adding connector actions Pause / Resume / Restart

---

ui/packages/ui/src/app/components/ConnectionPropertiesError.tsx
ui/packages/ui/src/app/components/formHelpers/FormComponent.tsx
ui/packages/ui/src/app/components/formHelpers/FormDurationComponent.tsx
ui/packages/ui/src/app/components/formHelpers/FormMaskHashSaltComponent.tsx
ui/packages/ui/src/app/components/formHelpers/FormMaskOrTruncateComponent.tsx
ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/DataOptionsComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/PropertiesStep.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/RuntimeOptionsComponent.tsx

Fixed the https://github.com/debezium/debezium-ui-poc/issues/281 issue 
- Updated the error display of `propertyValidationResults` type error.
- Invalid fields are being highlighted along with msg shown in the helper text.
- Updated the ConnectorPropertiesError component
FYI issue for `Postgres` connector fields with the `database` will be fixed in https://issues.redhat.com/browse/DBZ-2971

Display error msg on invalid fields

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConnectorNameTypeHeader.css
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConnectorNameTypeHeader.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConnectorTypeComponent.css
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConnectorTypeComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/PropertiesStep.css
ui/packages/ui/src/app/pages/createConnector/connectorSteps/PropertiesStep.tsx

- Adds display of the connector type on the basic properties page, underneath the name input (see images below)
- Adds header showing the connector name/type on the subsequent wizard pages (see images below)
- changed activeStep.name comparisons in CreateConnectorComponent to activeStep.id comparison.  Think this would be more reliable, since some of the names are actually elements - not strings.
**_Connection Props step:_**
**_Subsequent wizard steps:_**

Adding display of connector type within wizard pages

---

ui/packages/ui/src/app/components/ConnectionPropertiesError.tsx
ui/packages/ui/src/app/i18n/locales/translations.en.json
ui/packages/ui/src/app/i18n/locales/translations.it.json
ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx

Added the `displayName(propery)` to generic error msg.

added the invalid property name in generic error msg

---

ui/packages/services/src/connector/connector.service.ts
ui/packages/ui/src/app/pages/connectors/ConnectorsTableComponent.tsx

- updates the connector state lifecycle service methods and adds the task method
- update the restart action enablement - should always be enabled
- add function in ConnectorsTableComponent which changes a connector state immediately upon success of the lifecycle change instead of waiting for periodic refresh

Update backend connector service calls

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConnectorNameTypeHeader.css
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConnectorNameTypeHeader.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConnectorTypeComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/PropertiesStep.css
ui/packages/ui/src/app/pages/createConnector/connectorSteps/PropertiesStep.tsx

Simplified display of connector type in the wizard, per UX request.
- type icon is no longer shown (added 'showIcon' property to components to allow hide or show)
- simplified the name / type displayed at top of wizard pages to remove the bold labels, added divider
**Properties step screenshot:**
**Steps 3+ screenshot:**

DBZ-3054 Improve connector type display

---

ui/packages/ui/src/app/pages/connectors/ConnectorTaskState.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorsTableComponent.tsx

Fixed issue [DBZ-3049](https://issues.redhat.com/browse/DBZ-3049)
- Converted `expandableRows` state to an array type, with value storing all the expanded row index.
- Fixed the value provided to `isOpen` props in the table row (`isOpen: expandedRows.includes(index*2),`)

fix auto expanding issue

---

ui/packages/ui/src/app/components/ApplicationErrorPage.css
ui/packages/ui/src/app/components/ApplicationErrorPage.tsx

Added the white-space to the `pre` tag so that the error detail msg does not print in long-line. 
screenshot

added white-space to pre tag in server error msg detail

---

README.md
backend/pom.xml
oc-demo/05-ui.yaml
pom.xml
ui/README.md
ui/package.json
ui/packages/ui/package.json
ui/packages/ui/webpack.common.js
ui/packages/ui/webpack.dev.js
ui/pom.xml

Initial changes for removing POC references.  The repo name will need to be changed to 'debezium-ui'.  Also the dockerhub image 'debezium-ui-poc'

DBZ-3027 - Remove POC references from UI

---

backend/src/main/resources/application.properties
ui/packages/models/src/ui.model.ts
ui/packages/services/src/connector/connector.service.ts
ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/FilterConfigComponent.tsx
ui/packages/ui/src/app/pages/createConnector/noValidation/CreateConnectorNoValidation.tsx
ui/packages/ui/tslint.json

Jira issue [DBZ-3314](https://issues.redhat.com/browse/DBZ-3314)  [DBZ-3255](https://issues.redhat.com/browse/DBZ-3255)
- Removed the `/connector/{cluster}/{connector-id})` call from the no-validation mode
- Updated the API end points for `/connector-types` with `/connector-types` only being used to get the connector basic info (name, if) and `/connector-types/{connector-type}` to get the passed connector propertie details.

DBZ-3255 & DBZ-3314

---

backend/src/main/java/io/debezium/configserver/model/ConnectorDefinition.java
backend/src/main/java/io/debezium/configserver/model/ConnectorType.java
backend/src/main/java/io/debezium/configserver/rest/ConnectorResource.java
backend/src/main/java/io/debezium/configserver/service/ConnectorIntegrator.java
backend/src/main/java/io/debezium/configserver/service/ConnectorIntegratorBase.java
ui/packages/models/src/ui.model.ts

backend:
connector-types - removes properties from the response
connector-types/{id} - now only returns the array of properties
ui:
remove properties attribute from the ConnectorType model
adjust the service and usages to account for the connector-types/{id} only returning properties array

DBZ-3316 Remove properties from connector-types response

---

ui/packages/ui/src/app/pages/connectors/ConnectorsTableComponent.tsx

Filtering out nulls from connectors list in the UI - in case the backend response has nulls mixed in.

DBZ-3580 - handle nulls in connectors response

---

backend/src/main/java/io/debezium/configserver/service/ConnectorIntegratorBase.java
backend/src/main/java/io/debezium/configserver/service/mysql/MySqlConnectorIntegrator.java
backend/src/test/java/io/debezium/configserver/ConnectorResourceIT.java

- Add filtering of null properties in the sort operation
- remove deprecated property from MySqlConnectorIntegrator
- adding test for null properties in ConnectorResourceIT

DBZ-3108 Filter out nulls in connector properties

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx

Corrects UI regression in the previous commit - RegEx was being used incorrectly.  After entering topic groups, proceeding to next step, then going back to topic groups step - the connector properties were not being maintained.  This commit removes the RegEx usage in favor of a different approach.

DBZ-4293 Corrects issue with UI step refresh

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx

This addresses the issue raised in DBZ-4119, plus a couple other issues with the create connector wizard:
1) DBZ-4119 - When user validates connection and goes directly to 'Review', now the LH menu 'Properties' step is enabled.
2) The LH menu selection was not always correctly indicated - this PR resolves
3) If user goes back to 'Properties' step and changes a connection property, the previously visited steps are invalidated and their properties removed.  The intent here is to prevent the case where the user can connect to a completely different db, rendering previously entered optional properties invalid (filter, topic group, etc).  They will now be required to revisit and re-enter those optional properties if the connection is changed.

DBZ-4119 Correct enablement of create connector steps

---

ui/packages/ui/src/app/pages/createConnector/connectorSteps/TopicCreationStep.tsx

Ensure that the topic group replication factor and partitions defaults are included whenever topic groups have been defined.  These two defaults are required whenever topic groups are defined, according to table 1 here - https://debezium.io/documentation/reference/configuration/topic-auto-create-config.html#default-topic-creation-group-configuration

DBZ-4378 Add required defaults when topic groups are defined

---

backend/src/main/java/io/debezium/configserver/service/mongodb/MongoDbConnectorIntegrator.java

Minor change to MongoDbConnectorIntegrator to eliminate null in the namespaces.
Before:
After:

DBZ-4540 Corrects issue with nulls in Mongo connector UI

---

backend/src/test/java/io/debezium/configserver/CreateAndDeleteMySqlConnectorIT.java
backend/src/test/java/io/debezium/configserver/CreateAndDeletePostgresConnectorIT.java
backend/src/test/java/io/debezium/configserver/LifecycleResourceIT.java
backend/src/test/java/io/debezium/configserver/ListPostgresConnectorIT.java
backend/src/test/java/io/debezium/configserver/ValidatePostgresFiltersIT.java
backend/src/test/java/io/debezium/configserver/util/Infrastructure.java

https://issues.redhat.com/browse/DBZ-5125

DBZ-5125 Remove spatial_ref_sys table from Postgres filter tests

---

.github/workflows/backend-testing.yml
.github/workflows/end-to-end-testing.yml
backend/pom.xml
backend/src/main/java/io/debezium/configserver/service/mongodb/MongoDbConnectorIntegrator.java
backend/src/main/java/io/debezium/configserver/service/mysql/MySqlConnectorIntegrator.java
backend/src/main/java/io/debezium/configserver/service/sqlserver/SqlServerConnectorIntegrator.java
backend/src/test/java/io/debezium/configserver/CreateAndDeleteSqlSeverConnectorIT.java
backend/src/test/java/io/debezium/configserver/ValidateSqlServerFiltersIT.java
backend/src/test/java/io/debezium/configserver/ValidateSqlSeverDatabasesIT.java
backend/src/test/java/io/debezium/configserver/util/Infrastructure.java
backend/src/test/resources/initialize-sqlserver-database.sql
pom.xml

https://issues.redhat.com/browse/DBZ-5317

DBZ-5317 Upgrade UI to 2.0

---

backend/src/test/java/io/debezium/configserver/util/Infrastructure.java

We execute init script once the container is started, but started container may not be initialized yet and e.g. setting CDC for tables may fail with:
Cannot perform this operation while SQLServerAgent is starting. Try again later.
This happens especially in CI where the machines are slower. Add startup strategy to wait for 5 seconds until container is considered as started.
https://issues.redhat.com/browse/DBZ-5613

DBZ-5613 Wait before SQL server container is considered as started

---

backend/src/main/java/io/debezium/configserver/rest/ConnectorResource.java
backend/src/test/java/io/debezium/configserver/ConnectorResourceIT.java

https://issues.redhat.com/browse/DBZ-5865
This adds the `connector.displayName` and `connector.id` to the config endpoint payload.  
@uidoyen let me know if this needs to be adjusted.

DBZ-5865 Add connector.displayName and connector.id to Config endpoint
