debezium/debezium-ui

ui/pom.xml

@mdrillin a quick one for building a JAR with the UI contents so we can publish it via the Quarkus backend.

Creating JAR for UI

---

ui/packages/ui/src/app/pages/createConnection/CreateConnectionPage.tsx
ui/packages/ui/src/app/pages/createConnection/SelectConnectorComponent.css
ui/packages/ui/src/app/pages/createConnection/SelectConnectorComponent.tsx
ui/packages/ui/src/app/pages/createConnection/index.ts
ui/packages/ui/src/app/pages/index.ts

Add the initial basic ui for select connector Step

Select connector page

---

README.md

- Updated readme page with DBZ build instructions required to build before building POC.

updated the readme with DBZ build instructions

---

ui/packages/ui/src/app/component/PageLoader.tsx
ui/packages/ui/src/app/component/index.ts
ui/packages/ui/src/app/pages/connectors/ConnectorsPage.css
ui/packages/ui/src/app/pages/connectors/ConnectorsPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/SelectConnectorTypeComponent.tsx
ui/packages/ui/src/app/shared/Utils.ts

- Added the wrapper function to make the fetch re-try in case of error.
- Carved out the Pageloader in a separate component.
- Update the ConnectorsPage(Landing page) as per UX design.

retry logic for api call

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/SelectConnectorTypeComponent.css
ui/packages/ui/src/app/pages/createConnector/connectorSteps/SelectConnectorTypeComponent.tsx
ui/yarn.lock

- Lifted the '/connector-types' call to CreateConnectorPage.
- Minor UI changes in SelectConnectorTypeComponent.

Lifting connector-type api call to createConnnectorPage

---

ui/package.json
ui/packages/ui/package.json
ui/packages/ui/src/app/app.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorListItem.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorsPage.tsx
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/SelectConnectorTypeComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/SelectTablesStep.css
ui/packages/ui/src/app/pages/createConnector/connectorSteps/SelectTablesStep.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/index.ts
ui/packages/ui/src/app/shared/PageNotFound.tsx
ui/packages/ui/src/app/shared/RenderRoutes.tsx
ui/packages/ui/src/app/shared/index.ts
ui/packages/ui/src/app/shared/routes.tsx
ui/packages/ui/src/app/shared/useRouteData.tsx
ui/yarn.lock

- Added the router config 
- integrated the PageNotFound component.
- added the react-router and react-router-dom to no-hoist for using react-router-dom hooks
- Added some basic SelectTablesStep Component.

Adding routing

---

ui/packages/ui/package.json
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConfigureConnectorTypeComponent.css
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConfigureConnectorTypeComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConfigureConnectorTypeForm.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/DbzLabelIcon.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/FormInputComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/index.ts

Adding Basic form for connector properties

Basic form for connector properties 

---

ui/packages/ui/src/app/Layout/AppLayout.tsx
ui/packages/ui/src/app/Layout/layout.css
ui/packages/ui/src/app/app.css

Adding a container to the layout

Layout container

---

ui/packages/ui/src/app/Layout/AppLayout.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConfigureConnectorTypeForm.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/DbzLabelIcon.tsx
ui/packages/ui/tslint.json

Fixing build error due to connector properties form.

fixing build error

---

ui/packages/ui/src/app/app.css
ui/packages/ui/src/app/pages/connectors/ConnectorsPage.css
ui/packages/ui/src/app/pages/connectors/ConnectorsPage.tsx
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.css
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/SelectConnectorTypeComponent.css
ui/packages/ui/src/app/pages/createConnector/connectorSteps/SelectConnectorTypeComponent.tsx

Improved UI in connector list and select connector page.

Tweaking UI

---

ui/packages/ui/src/app/Layout/Breadcrumb.tsx
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.css
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConnectorTypeStepComponent.css

- Added the page heading to create connector page.

Added page heading in create connector

---

backend/pom.xml
backend/src/main/java/io/debezium/configserver/model/ConnectorConfig.java
backend/src/main/java/io/debezium/configserver/rest/ConnectorResource.java
backend/src/main/java/io/debezium/configserver/rest/client/KafkaConnectClient.java
backend/src/main/java/io/debezium/configserver/service/postgres/PostgresConnectorIntegrator.java
backend/src/main/resources/application.properties
backend/src/test/java/io/debezium/configserver/ConnectorResourceIT.java
backend/src/test/java/io/debezium/configserver/CreatePostgresConnectorIT.java
backend/src/test/java/io/debezium/configserver/MultipleKafkaConnectClustersIT.java
backend/src/test/java/io/debezium/configserver/NativeCreatePostgresConnectorIT.java
backend/src/test/java/io/debezium/configserver/NativeMultipleKafkaConnectClustersIT.java
backend/src/test/java/io/debezium/configserver/util/Infrastructure.java
backend/src/test/java/io/debezium/configserver/util/MultipleKafkaConnectClustersTestProfile.java
backend/src/test/java/io/debezium/configserver/util/PostgresInfrastructureTestProfile.java
backend/src/test/java/io/debezium/configserver/util/PostgresInfrastructureTestResourceLifecycleManager.java
pom.xml

Add "create connector" enpoint

Add "create connector" endpoint

---

backend/src/main/java/io/debezium/configserver/model/KafkaConnectClusterList.java
backend/src/main/java/io/debezium/configserver/rest/ConnectorResource.java

@gunnarmorling I quickly added some annotations so that the Swagger UI shows the response data structure nicely in the cases where the return type is only Resonse and Swagger doesn't know the return type.

Add swagger response metadata for proper swagger UI description

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConfigureConnectorTypeForm.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/dataOptions/DataOptionsComponent.css
ui/packages/ui/src/app/pages/createConnector/connectorSteps/dataOptions/DataOptionsComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/dataOptions/DataOptionsForm.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/dataOptions/index.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/index.ts
ui/packages/ui/src/app/pages/createConnector/connectorSteps/shared/DbzLabelIcon.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/shared/FormInputComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/shared/FormSelectComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/shared/index.tsx

- Added data options form with basic setup.
- Snapshot Properties TBD

Adding data options form

---

ui/packages/ui/package.json
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConnectorTypeStepComponent.css
ui/packages/ui/src/app/pages/createConnector/connectorSteps/FiltersStepComponent.css
ui/packages/ui/src/app/pages/createConnector/connectorSteps/FiltersStepComponent.tsx
ui/yarn.lock

-  Added UI for Filters Step
-  Update the @patternfly version to use the TreeView component.
Will handle backend integration in subsequent pr.

adding inital ui code

---

ui/packages/ui/package.json
ui/packages/ui/src/app/pages/createConnector/connectorSteps/FiltersStepComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/shared/FormInputComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/shared/FormSwitchComponent.tsx
ui/yarn.lock

- Build fixes.
- Updated the TS to fix formik import warning. https://github.com/formium/formik/issues/1631

Build fix and TS update

---

ui/packages/ui/src/app/components/FilterTreeComponent.tsx
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConnectorTypeStepComponent.css
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConnectorTypeStepComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/FiltersStepComponent.css
ui/packages/ui/src/app/pages/createConnector/connectorSteps/FiltersStepComponent.tsx
ui/packages/ui/webpack.dev.js

- Update the UI for Invalid filter, No matching content.
- Removed the switch and introduced the toggle for include/exclude.
- Uplifted the filter values to the conectConnectorPage and implement entered value persistence in moving next/back.
- Updated the bg color for disabled connector card.

Fixed the filter page issues

---

ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConfigureConnectorTypeForm.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/dataOptions/DataOptionsComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/dataOptions/DataOptionsForm.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/shared/FormCheckboxComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/shared/FormSelectComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/shared/index.tsx
ui/packages/ui/src/app/shared/CategoryUtil.ts

- Added Select type component
- Added Checkbox component
- Added Switch component
- Added input type properties based on UI under Category Utils
Note: Added static options value to fill the drop-down for now, Will remove those with actually values

Data Options Form based on properties

---

ui/packages/ui/src/app/pages/createConnector/connectorSteps/dataOptions/DataOptionsForm.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/shared/FormSelectComponent.tsx
ui/packages/ui/src/app/shared/CategoryUtil.ts

- Moved Snapshot properties section at the top
- Modified FormSelectComponent to pash allowedValues
- Replaced static drop down values with the actual one(allowedValues)

Re-positioning the properties section

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConfigureConnectorTypeComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConfigureConnectorTypeForm.tsx

- Wired the property page forms
- Removed the hardcoded value for filter request.

Updated the property step and filter request payload

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConfigureConnectorTypeComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/FiltersStepComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/dataOptions/DataOptionsComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/runtimeOptions/RuntimeOptionsComponent.tsx

- added the validation on the data and runtime option page.

validation on data and runtime options page

---

README.md
docker-compose.yml

+ add docker-compose dev infrastructure (Zookeeper, Kafka, Debezium, Postgres)
closes #57

Add docker-compose dev infrastructure

---

ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConfigureConnectorTypeComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/dataOptions/DataOptionsComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/runtimeOptions/RuntimeOptionsComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/shared/FormInputComponent.tsx

- setting FormInputComponent type based upon the property type
- if property type INT or LONG and no defaultValue, setting initial value of 0

Adjustments for numeric in form

---

ui/packages/ui/src/app/Layout/appHeader.tsx
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConfigureConnectorTypeComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/dataOptions/DataOptionsComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/runtimeOptions/RuntimeOptionsComponent.tsx

- Route to home on clicking of "Debezium" logo.
- Validation update on the last two pages.
- User entered value persistence on the last two steps.
- Disable the "back" button on the first step.

minor fixes and validation update on last two steps

---

ui/packages/ui/src/app/components/FilterTreeComponent.tsx
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/FiltersStepComponent.tsx
ui/packages/ui/src/app/shared/Utils.ts

Made some wording changes, mostly around the table selection and filtering.

Some wording updates, mostly regarding table selection / filtering

---

ui/packages/ui/src/app/components/FilterTreeComponent.tsx
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/FiltersStepComponent.tsx

- Added option to skip and last 3 steps and early finish.
- Disable the Next and Finish button on the filter page for the invalid scenarios.
- Screenshots.

added early finish option and disable filter next for invalid case

---

ui/packages/ui/src/app/Layout/AppLayout.tsx
ui/packages/ui/src/app/Layout/AppLayoutContext.tsx
ui/packages/ui/src/app/Layout/appHeader.tsx
ui/packages/ui/src/app/Layout/layout.css
ui/packages/ui/src/app/components/KafkaConnectCluster.tsx
ui/packages/ui/src/app/components/index.ts
ui/packages/ui/src/app/pages/connectors/ConnectorsPage.tsx
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.css

- Moving the cluster dropdown into the header
- Fixing wizard nav items not highlighting correctly

Moving the cluster dropdown into the header

---

ui/packages/ui/src/app/components/ToastAlertComponent.tsx
ui/packages/ui/src/app/components/index.ts
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx

- Remove the error Toast msg automatically after 10 sec.
- Moved the Toast msg in a different component.

Remove the error toast msg after 10 sec

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.css
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConfigureConnectorComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/DataOptionsComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/RuntimeOptionsComponent.tsx

Removing extra title for expansion area in Properties, Data Options and Runtime Options steps

Fixing expansion panel

---

ui/packages/ui/src/app/pages/connectors/ConnectorListItem.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorStatus.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorTasks.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorsPage.css

- Added connectors tasks component
- Added Tooltip to show connector status
- Moved "Create a Connector" button to the left
- Moved the connector name to the left

Connector list improvements

---

ui/packages/ui/src/app/components/ToastAlertComponent.tsx
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx

- Added option to manually remove the error toast msg.

adding option to manually remove the error toast msg

---

ui/packages/ui/src/app/pages/connectors/ConnectorsPage.tsx
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConnectorTypeStepComponent.css

- Set card headers to same height, to better align card text
- Add check of connector name to avoid duplicate - checks entry against already existing connector names

align connector type card text, add connector name check

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx

- Asking the user to validate the "Data option" & "Runtime option" page only if any changes are being made to them.

showing the Next button for default values on landing -last 2 steps

---

backend/src/main/java/io/debezium/configserver/model/ConnectorStatus.java
backend/src/test/java/io/debezium/configserver/ListPostgresConnectorIT.java

Make connectorType strings consistent

---

backend/src/main/java/io/debezium/configserver/model/ConnectTaskStatus.java
backend/src/main/java/io/debezium/configserver/model/ConnectorStatus.java
backend/src/main/java/io/debezium/configserver/model/FrontendConfig.java
backend/src/main/java/io/debezium/configserver/model/FrontendConfigArtifacts.java
backend/src/main/java/io/debezium/configserver/model/TaskStatus.java
backend/src/main/java/io/debezium/configserver/rest/ConnectorResource.java
backend/src/main/java/io/debezium/configserver/rest/FrontendConfigResource.java
backend/src/test/java/io/debezium/configserver/ListPostgresConnectorIT.java
backend/src/test/java/io/debezium/configserver/util/DebeziumContainer.java
ui/config/config.js
ui/packages/services/src/config/config.service.ts
ui/packages/ui/src/app/pages/connectors/ConnectorListItem.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorTask.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorsPage.css

+ add task errors to UI backend
+ add task errors to UI frontend tooltips
* fix config issue in prod / UI-backend mode
closes #180

Add task errors to UI backend, fix config issue

---

backend/src/main/java/io/debezium/configserver/rest/ConnectorResource.java
backend/src/main/java/io/debezium/configserver/rest/client/KafkaConnectClient.java
backend/src/test/java/io/debezium/configserver/CreateAndDeletePostgresConnectorIT.java
backend/src/test/java/io/debezium/configserver/NativeCreateAndDeletePostgresConnectorIT.java

Add delete connector endpoint

---

ui/packages/services/src/connector/connector.service.ts
ui/packages/ui/src/app/pages/connectors/ConnectorListItem.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorsPage.tsx

- Hooked up the `/api/connectors/{cluster}/{connector-name}` to delete button on the connector list.
- Added the polling to `/api/connectors/{cluster}` to get the updated list of connector at the interval of 10 sec

Added the polling to create connector page and hooked up delete button

---

ui/packages/ui/src/app/app.tsx
ui/packages/ui/src/app/components/PageNotFound.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorListItem.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorsPage.tsx
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/shared/routes.tsx

added the hash`#` in route for bypassing the unknown URI issue altogether.

Hash route

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx

A few minor fixes from UX feedback
- fix case on wizard steps and breadcrumbs
- change to inline alert style and move above wizard buttons
- added 'Optional' label on wizard 'Additional properties' step (left commented out pending UX input)

Minor fixes in Create Connector Wizard

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx

- Updated the validate & next button position as per UX feedback

Updating the validate & next button position as per UX feedback

---

ui/README.md
ui/packages/ui/package.json
ui/packages/ui/src/app/components/BasicSelectInput.css
ui/packages/ui/src/app/components/BasicSelectInput.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorListItem.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/TableSelectionStep.tsx
ui/packages/ui/src/app/shared/ConfirmationDialog.tsx
ui/yarn.lock

Addresses issue #198 , partial #197 
- update the patternfly version to get updates to modal
- made updates to ConfirmationDialog, allows dialog to choose the correct title icon based upon the type
- change dialog title to sentence case per UX request
- minor update to readme to specify node version requirement
- add styling to kafka connect selector
- updated ToggleGroupItems required due to patternfly update

dialog and readme updates

---

ui/packages/ui/src/app/pages/createConnector/connectorSteps/TableSelectionStep.tsx

Partial fixes of  https://github.com/debezium/debezium-ui-poc/issues/201

Ux changes

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.css
ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConnectorTypeStepComponent.css
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConnectorTypeStepComponent.tsx

- Added the asterisk (*) to indicate the required steps
- Added coming soon label to upcoming connector types

Adding coming soon label and asterisk

---

ui/packages/ui/src/app/pages/createConnector/connectorSteps/TableSelectionStep.tsx

Updated the placeholder text as per suggestion.
screenshot

updating placeholder

---

ui/packages/ui/src/app/pages/connectors/ConnectorsTableComponent.tsx

Reverting change in prior PR.  Was in error - my backend code was out-of-date

Revert erroneous change to taskState

---

ui/packages/ui/package.json
ui/packages/ui/src/app/app.tsx
ui/packages/ui/src/app/i18n/index.ts
ui/packages/ui/src/app/i18n/locales/index.ts
ui/packages/ui/src/app/i18n/locales/translations.en.json
ui/packages/ui/src/app/i18n/locales/translations.it.json
ui/packages/ui/src/app/pages/connectors/ConnectorsTableComponent.tsx
ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/DataOptionsComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/PropertiesStep.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ReviewStepComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/RuntimeOptionsComponent.tsx
ui/yarn.lock

Adding capability for i18n support.  Created a couple translation files and started to convert titles/messages in some of the components.

Adding i18n support

---

ui/packages/ui/src/app/pages/connectors/ConnectorsTableComponent.tsx

Implemented the sorted connector name direction toggle.

toolbar sort direction toggle

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx

Added Pr for https://github.com/debezium/debezium-ui-poc/issues/67 Github issue
- Added the Wizard Exit confirmation dialog on the browser back button so that the user is warned of losing all the entered values before moving to the connector list page.

Added the wizard exit confirmation dialog on the browser back button

---

ui/packages/services/package.json
ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx
ui/yarn.lock

Upgrading axios ; fix lint issue with imports

axios upgrade and lint fix

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx

Fixed the issue https://github.com/debezium/debezium-ui-poc/issues/257
- Updated the wizard navigation call function form `goToStepByName` to `goToStepById`
_(after adding the required red asterisk mark work on steps name, some of the wizard names were no longer the string values)_

Fixed the wizard back button issue

---

ui/packages/ui/src/app/components/formHelpers/FormComponent.tsx
ui/packages/ui/src/app/components/formHelpers/FormMaskOrTruncateComponent.css
ui/packages/ui/src/app/components/formHelpers/FormMaskOrTruncateComponent.tsx
ui/packages/ui/src/app/components/formHelpers/MaskOrTruncateItem.css
ui/packages/ui/src/app/components/formHelpers/MaskOrTruncateItem.tsx
ui/packages/ui/src/app/i18n/locales/translations.en.json
ui/packages/ui/src/app/i18n/locales/translations.it.json

- fix lint issue with previous commit
- improvements to column mask-truncate component (adding tooltips / improve styling)

fix build; mask-truncate improvements

---

ui/package.json
ui/yarn.lock

Pr for GitHub issue https://github.com/debezium/debezium-ui-poc/issues/259
This will add the build process in git pre-commit

Husky setup

---

ui/packages/ui/src/app/i18n/locales/translations.en.json
ui/packages/ui/src/app/i18n/locales/translations.it.json
ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/PropertiesStep.tsx

- minor changes for properties step - validation and title displays
- i18n a couple sub-titles on the step

UI fixes for Mongo properties

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx
ui/packages/ui/src/app/shared/Utils.ts

- Adds new MongoDB connector properties to UI.
- adapts the Utils function for formatting the properties to recognize connector type and format accordingly.

Adding mongo connector properties to UI

---

ui/packages/models/src/ui.model.ts
ui/packages/ui/src/app/components/formHelpers/FormInputComponent.tsx
ui/packages/ui/src/app/i18n/locales/translations.en.json
ui/packages/ui/src/app/i18n/locales/translations.it.json
ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx
ui/packages/ui/src/app/shared/Utils.ts

Addresses Issue #278 
- added handling for GenericValidationResults in CreateConnectorComponent
- some numeric inputs require positive int - added POS-INT type and sets a different min value for those on FormInputComponent
- fix issue in CreateConnectorComponent, was checking DataOptions instead of RuntimeOptions

Handling for generic validation error

---

ui/packages/ui/src/app/components/ApplicationErrorPage.tsx
ui/packages/ui/src/app/components/FilterTreeComponent.tsx
ui/packages/ui/src/app/i18n/locales/translations.en.json
ui/packages/ui/src/app/i18n/locales/translations.it.json
ui/packages/ui/src/app/pages/connectors/ConnectorsPage.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorsTableComponent.tsx
ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConnectorTypeStepComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/FilterConfigComponent.tsx
ui/packages/ui/src/app/shared/ApiError.tsx

Address issue #290 
- FilterConfigComponent now clears any errors when filters cleared or applied
- changes in ApplicationErrorPage to i18n some text, better display of error details

addresses filter result errors

---

backend/src/main/java/io/debezium/configserver/rest/ConnectorResource.java
backend/src/main/java/io/debezium/configserver/rest/ConnectorURIs.java
backend/src/main/java/io/debezium/configserver/rest/KafkaConnectClientException.java
backend/src/main/java/io/debezium/configserver/rest/KafkaConnectClientExceptionMapper.java
backend/src/main/java/io/debezium/configserver/rest/KafkaConnectExceptionMapper.java
backend/src/main/java/io/debezium/configserver/rest/LifecycleResource.java
backend/src/main/java/io/debezium/configserver/rest/client/InvalidClusterException.java
backend/src/main/java/io/debezium/configserver/rest/client/KafkaConnectClient.java
backend/src/main/java/io/debezium/configserver/rest/client/KafkaConnectClientFactory.java
backend/src/main/java/io/debezium/configserver/rest/client/KafkaConnectException.java
backend/src/main/java/io/debezium/configserver/rest/model/NotFoundResponse.java
backend/src/main/java/io/debezium/configserver/service/StacktraceHelper.java
backend/src/test/java/io/debezium/configserver/ConnectorResourceIT.java
backend/src/test/java/io/debezium/configserver/CreateAndDeleteMongoDbConnectorIT.java
backend/src/test/java/io/debezium/configserver/CreateAndDeletePostgresConnectorIT.java
backend/src/test/java/io/debezium/configserver/LifecycleResourceIT.java
backend/src/test/java/io/debezium/configserver/ListPostgresConnectorIT.java
backend/src/test/java/io/debezium/configserver/MultipleKafkaConnectClustersIT.java
backend/src/test/java/io/debezium/configserver/NativeLifecycleResourceIT.java
backend/src/test/java/io/debezium/configserver/ValidateMongoDbFiltersIT.java
backend/src/test/java/io/debezium/configserver/ValidatePostgresConnectionIT.java
backend/src/test/java/io/debezium/configserver/ValidatePostgresFiltersIT.java
backend/src/test/java/io/debezium/configserver/util/AbstractInfrastructureTestResourceLifecycleManager.java
backend/src/test/java/io/debezium/configserver/util/MultipleKafkaConnectClustersTestProfile.java

closes https://issues.redhat.com/browse/DBZ-2951

DBZ-2951 Add Connector and Connector-Task lifecycle management

---

ui/packages/ui/src/app/components/FilterTreeComponent.tsx
ui/packages/ui/src/app/i18n/locales/translations.en.json
ui/packages/ui/src/app/i18n/locales/translations.it.json
ui/packages/ui/src/app/pages/createConnector/connectorSteps/FilterConfigComponent.tsx

- Added the column/field filter being applied info in the filter page alerts.
- Moved the filter page alert from `FilterConfigComponent` to `FilterTreeComponent` to remove the multiple spinners.
screenshot

Filter alerts

---

ui/packages/ui/src/app/i18n/locales/translations.en.json
ui/packages/ui/src/app/i18n/locales/translations.it.json
ui/packages/ui/src/app/pages/connectors/ConnectorOverview.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorStatus.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorTask.css
ui/packages/ui/src/app/pages/connectors/ConnectorTask.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorTaskState.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorsPage.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorsTableComponent.css
ui/packages/ui/src/app/pages/connectors/ConnectorsTableComponent.tsx

- Implemented connector items expandable.
- Added total task count based on task status.
- Added individual task restart and popover.
Connector overview message is static for now.

Making connector list items expandable

---

ui/packages/ui/package.json
ui/packages/ui/src/app/pages/connectors/ConnectorsTableComponent.tsx
ui/yarn.lock

Fix for the connector page auto-refresh issue.

Connector refresh

---

ui/packages/ui/src/app/i18n/locales/translations.en.json
ui/packages/ui/src/app/i18n/locales/translations.it.json
ui/packages/ui/src/app/pages/connectors/ConnectorTask.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorsTableComponent.css
ui/packages/ui/src/app/pages/connectors/ConnectorsTableComponent.tsx

- Fix alignment issue on mobile
- Add info icon to FAILED Status
- Hide kebab menu icon on expanded panel

DBZ-3079 Connector list UI fix on mobile

---

README.md
backend/pom.xml
backend/src/main/java/io/debezium/configserver/service/mongodb/MongoDbConnectorIntegrator.java
backend/src/main/java/io/debezium/configserver/service/mysql/MySqlConnectorIntegrator.java
backend/src/main/java/io/debezium/configserver/service/postgres/PostgresConnectorIntegrator.java
backend/src/main/resources/META-INF/services/io.debezium.configserver.service.ConnectorIntegrator
backend/src/test/java/io/debezium/configserver/ConnectorResourceIT.java
backend/src/test/java/io/debezium/configserver/CreateAndDeleteMySqlConnectorIT.java
backend/src/test/java/io/debezium/configserver/CreateAndDeletePostgresConnectorIT.java
backend/src/test/java/io/debezium/configserver/NativeCreateAndDeleteMySqlConnectorIT.java
backend/src/test/java/io/debezium/configserver/ValidateMySqlFiltersIT.java
backend/src/test/java/io/debezium/configserver/util/AbstractInfrastructureTestResourceLifecycleManager.java
backend/src/test/java/io/debezium/configserver/util/Infrastructure.java
backend/src/test/java/io/debezium/configserver/util/MongoDbContainer.java
backend/src/test/java/io/debezium/configserver/util/MySqlInfrastructureTestProfile.java
backend/src/test/java/io/debezium/configserver/util/MySqlInfrastructureTestResourceLifecycleManager.java
docker-compose.yml
pom.xml
ui/pom.xml

closes https://issues.redhat.com/browse/DBZ-2950

DBZ-2950 Add MySQL Connector to UI backend

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/PropertiesStep.tsx
ui/packages/ui/src/app/shared/Utils.ts

Null check on UI for defective properties value(null)

null check on ui for weeding out backend null prop value

---

ui/packages/ui/src/app/shared/Utils.ts

Adds layout formatting for MySQL properties to Utils function.  Also addition of some missing property names, corrections and improvements.

DBZ-3091 Adds MySQL property handling in UI Utils

---

ui/packages/ui/src/app/pages/createConnector/connectorSteps/FilterConfigComponent.tsx
ui/packages/ui/src/app/shared/ConfirmationDialog.tsx
ui/packages/ui/src/app/shared/Utils.ts

covered sub-task in [DBZ-3091](https://issues.redhat.com/browse/DBZ-3091)
- Added the filter handle for MySQL connector in utils.ts
- Fix for console error in `ConfirmationDialog` & `FilterConfigComponent`

Mysql filter

---

ui/packages/ui/src/app/components/formHelpers/MaskHashSaltItem.tsx
ui/packages/ui/src/app/components/formHelpers/MaskOrTruncateItem.tsx
ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.css
ui/packages/ui/src/app/pages/createConnector/connectorSteps/DataOptionsComponent.css

- Improve layout for Data options component, switch buttons overlapping on mobile
- Reduced main wizard sub nav item gape
- Fixed layout for Column Truncate in Mask Component

DBZ-3105 Layout improvement

---

ui/packages/models/src/ui.model.ts
ui/packages/ui/src/app/Layout/AppLayoutContext.tsx
ui/packages/ui/src/app/components/BasicSelectInput.tsx
ui/packages/ui/src/app/components/KafkaConnectCluster.tsx
ui/packages/ui/src/app/components/formHelpers/FormSelectComponent.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorIcon.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorStatus.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorTask.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorTaskState.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorsPage.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorsTableComponent.tsx
ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx
ui/packages/ui/src/app/pages/createConnector/CreateConnectorPage.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConnectorTypeComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConnectorTypeStepComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/DataOptionsComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/FilterConfigComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/PropertiesStep.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/ReviewStepComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/RuntimeOptionsComponent.tsx
ui/packages/ui/src/app/shared/Utils.ts

Fixed the lint issues in UI code.

Fixed the pending lint issues in UI application

---

ui/packages/ui/package.json
ui/packages/ui/webpack.prod.js
ui/yarn.lock

Use `css-minimizer-webpack-plugin` instead of `Optimize CSS Assets Webpack Plugin` for Webpack 5

add css-minimizer-webpack-plugin for Webpack 5

---

README.md

There is no preview of the UI in the readme.

DOC - Add WEB UI screenshot

---

.github/workflows/end-to-end-testing.yml
Dockerfile

closes https://issues.redhat.com/browse/DBZ-3453

DBZ-3453 Fix permissions for Cypress builds for users that are root or not having user id 1001

---

ui/packages/ui/assets/mockResponce/PostgresConnector.json
ui/packages/ui/src/app/pages/createConnector/noValidation/debezium/DataOptions.tsx
ui/packages/ui/src/app/pages/createConnector/noValidation/debezium/DebeziumConfigurator.tsx
ui/packages/ui/src/app/pages/createConnector/noValidation/debezium/FiltersDefinition.tsx
ui/packages/ui/src/app/pages/createConnector/noValidation/debezium/Helper/FormInputComponent.tsx
ui/packages/ui/src/app/pages/createConnector/noValidation/debezium/Helper/HelpInfoIcon.tsx
ui/packages/ui/src/app/pages/createConnector/noValidation/debezium/Properties.tsx
ui/packages/ui/src/app/pages/createConnector/noValidation/debezium/RuntimeOptions.tsx
ui/packages/ui/src/app/pages/createConnector/noValidation/debezium/config.ts
ui/packages/ui/tslint.json
ui/packages/ui/webpack.common.js

federated component

---

ui/packages/ui/src/app/components/formHelpers/FormDurationComponent.tsx
ui/packages/ui/src/app/components/formHelpers/FormSelectComponent.tsx

Fixing FormDurationComponent & FormSelectComponent issues

Fixing FormDurationComponent & FormSelectComponent issue

---

ui/packages/ui/src/app/pages/createConnector/noValidation/debezium/DataOptions.tsx
ui/packages/ui/src/app/pages/createConnector/noValidation/debezium/DebeziumConfigurator.tsx
ui/packages/ui/src/app/pages/createConnector/noValidation/debezium/RuntimeOptions.tsx

- fix incorrect translation being supplied in DebeziumConfigurator
- remove commented sections in DataOptions and RuntimeOptions

fixes issue with supplied translation

---

ui/packages/ui/src/app/components/FilterExcludeFieldComponent.tsx
ui/packages/ui/src/app/components/FilterInputFieldComponent.tsx

Issue:- https://issues.redhat.com/browse/DBZ-3102

DBZ-3102: Disable the toggle if no value is entered in input field

---

ui/packages/models/tsconfig.json
ui/packages/models/tslint.json
ui/packages/models/webpack.config.js
ui/packages/services/src/baseService.ts
ui/packages/services/src/services.ts
ui/packages/services/tsconfig.json
ui/packages/services/tslint.json
ui/packages/ui/package.json
ui/packages/ui/tsconfig.json
ui/tsconfig.build.json
ui/tsconfig.json
ui/tsconfig.test.json
ui/yarn.lock

- Updated `tslib`
- Added common `compilerOptions` to avoid repeatation
- Added `tsconfig` for testing

Updating TypeScript Compiler Configuration

---

ui/packages/ui/src/app/components/connectorStepHelpers/RuntimeOptionsComponent.tsx
ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/PropertiesStep.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/RuntimeOptionsStep.tsx
ui/packages/ui/src/app/pages/createConnector/federatedModule/DebeziumConfigurator.tsx
ui/packages/ui/src/app/pages/createConnector/federatedModule/Properties.tsx
ui/packages/ui/src/locales/en/public.json
ui/packages/ui/src/locales/it/public.json

Internationalization of error msg text

---

ui/packages/ui/src/app/pages/createConnector/federatedModule/DebeziumConfigurator.tsx

updates the type handling in the configurator to accommodate the json schema changes for connector passwords.

DBZ-3637 update schema handling in configurator

---

ui/packages/ui/src/app/pages/createConnector/federatedModule/DataOptions.tsx
ui/packages/ui/src/app/pages/createConnector/federatedModule/DebeziumConfigurator.tsx
ui/packages/ui/src/app/pages/createConnector/federatedModule/Properties.tsx
ui/packages/ui/src/app/pages/createConnector/federatedModule/RuntimeOptions.tsx
ui/packages/ui/src/app/shared/Utils.ts

- Break-fix and removing the unused props.

Remove name mcs

---

ui/packages/ui/src/app/pages/createConnector/federatedModule/DataOptions.tsx
ui/packages/ui/src/app/pages/createConnector/federatedModule/Properties.tsx
ui/packages/ui/src/app/pages/createConnector/federatedModule/RuntimeOptions.tsx

Add the required properties with default values in the final configurator JSON, even if values are not modified.

Fix for required properties with default values

---

ui/packages/ui/src/app/pages/createConnector/connectorSteps/FilterConfigStep.css
ui/packages/ui/src/app/pages/createConnector/federatedModule/DataOption.css
ui/packages/ui/src/app/pages/createConnector/federatedModule/DataOptions.tsx
ui/packages/ui/src/app/pages/createConnector/federatedModule/FilterConfig.css
ui/packages/ui/src/app/pages/createConnector/federatedModule/FilterConfig.tsx
ui/packages/ui/src/app/pages/createConnector/federatedModule/Properties.css
ui/packages/ui/src/app/pages/createConnector/federatedModule/Properties.tsx
ui/packages/ui/src/app/pages/createConnector/federatedModule/RuntimeOptions.css
ui/packages/ui/src/app/pages/createConnector/federatedModule/RuntimeOptions.tsx

- Fixing the federated module steps style disturbed by changes in the host app.
- Fixing the toggle button after PF update.
current

style fix for federatedModule

---

ui/packages/ui/__tests__/components/ApplicationErrorPage.test.tsx
ui/packages/ui/__tests__/components/ConnectionPropertiesError.test.tsx
ui/packages/ui/__tests__/components/KafkaConnectCluster.test.tsx
ui/packages/ui/__tests__/components/PageNotFound.test.tsx
ui/packages/ui/__tests__/components/ToastAlertComponent.test.tsx
ui/packages/ui/__tests__/layout/AppHeader.test.tsx
ui/packages/ui/__tests__/shared/ApiError.test.tsx
ui/packages/ui/__tests__/shared/ConfirmationDialog.test.tsx
ui/packages/ui/__tests__/shared/Utils.test.tsx
ui/packages/ui/assets/test/connector-properties.ts
ui/packages/ui/src/app/components/PageNotFound.tsx
ui/packages/ui/src/app/shared/ConfirmationDialog.tsx

Adding more ui component tests

DBZ-3050 Adding ui component tests

---

ui/packages/ui/__tests__/components/connectorStepHelpers/ConnectorNameTypeHeader.test.tsx
ui/packages/ui/__tests__/components/connectorStepHelpers/NoPreviewFilterField.test.tsx
ui/packages/ui/__tests__/components/formHelpers/FormCheckboxComponent.test.tsx
ui/packages/ui/__tests__/components/formHelpers/FormDurationComponent.test.tsx
ui/packages/ui/__tests__/components/formHelpers/FormInputComponent.test.tsx
ui/packages/ui/__tests__/components/formHelpers/FormMaskHashSaltComponent.test.tsx
ui/packages/ui/__tests__/components/formHelpers/FormMaskOrTruncateComponent.test.tsx
ui/packages/ui/__tests__/components/formHelpers/FormSelectComponent.test.tsx
ui/packages/ui/__tests__/components/formHelpers/FormSwitchComponent.test.tsx
ui/packages/ui/__tests__/pages/connectors/ConnectorOverview.test.tsx
ui/packages/ui/__tests__/pages/connectors/ConnectorStatus.test.tsx
ui/packages/ui/__tests__/pages/connectors/ConnectorTask.test.tsx
ui/packages/ui/__tests__/pages/connectors/ConnectorTaskState.test.tsx
ui/packages/ui/__tests__/shared/Utils.test.tsx
ui/packages/ui/src/app/components/formHelpers/FormMaskHashSaltComponent.tsx
ui/packages/ui/src/app/components/formHelpers/FormMaskOrTruncateComponent.tsx
ui/packages/ui/src/app/pages/connectors/ConnectorsTableComponent.tsx

Adding tests for more of the lower level components.  They are mostly just basic tests to render the components - we can improve the coverage over time.

Adding more component tests

---

ui/package.json
ui/packages/ui/__tests__/layout/AppHeader.test.tsx
ui/packages/ui/__tests__/layout/AppLayout.test.tsx
ui/packages/ui/src/app/app.tsx
ui/packages/ui/src/app/components/BasicSelectInput.tsx
ui/packages/ui/src/app/components/KafkaConnectCluster.tsx
ui/packages/ui/src/app/layout/AppHeader.tsx
ui/packages/ui/src/app/layout/layout.css
ui/yarn.lock

Improve header UI and enable Patternfly utilities classes

---

ui/packages/ui/src/app/pages/createConnector/connectorSteps/ReviewStep.tsx
ui/packages/ui/src/app/shared/Utils.ts

adding option to view the password on review page

---

.github/workflows/backend-testing.yml
.github/workflows/end-to-end-testing.yml
backend/pom.xml
backend/src/main/java/io/debezium/configserver/service/postgres/PostgresConnectorIntegrator.java
backend/src/test/java/io/debezium/configserver/util/Infrastructure.java
docker-compose.yml
pom.xml

closes https://issues.redhat.com/browse/DBZ-3837

DBZ-3837 upgrade Debezium UI to Debezium 1.6.1.Final

---

ui/packages/ui/src/app/shared/Utils.ts

Fixes issue with removal properties that have defaults.  The check in Utils.minimizePropertyValues was incorrect.

DBZ-3967 Fix issue with removal of default properties

---

ui/packages/ui/src/app/components/topicCreationHelpers/TopicDefaults.tsx
ui/packages/ui/src/app/components/topicCreationHelpers/TopicGroupCard.tsx
ui/packages/ui/src/app/components/topicCreationHelpers/TopicGroupConfig.tsx
ui/packages/ui/src/app/components/topicCreationHelpers/TopicGroupOptionItem.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/TopicCreationStep.tsx

https://issues.redhat.com/browse/DBZ-4172

DBZ-4172: Validate group name and prevent dublicate options

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx
ui/packages/ui/src/app/shared/Utils.ts

Encountered issues in firefox browser due to usages of 'replaceAll' javascript function.
Reworked the 'replaceAll' usages to instead use the 'replace' function.

DBZ-4274 Rework usages of replaceAll in frontend

---

.github/workflows/end-to-end-testing.yml
backend/src/main/java/io/debezium/configserver/model/FrontendConfig.java
backend/src/main/java/io/debezium/configserver/model/FrontendConfigArtifacts.java
backend/src/main/java/io/debezium/configserver/rest/FrontendConfigResource.java
backend/src/main/java/io/debezium/configserver/rest/client/KafkaConnectClientFactory.java
backend/src/main/resources/application.properties
backend/src/test/java/io/debezium/configserver/CreateAndDeletePostgresConnectorIT.java
backend/src/test/java/io/debezium/configserver/LifecycleResourceIT.java
backend/src/test/java/io/debezium/configserver/util/AbstractInfrastructureTestResourceLifecycleManager.java
backend/src/test/java/io/debezium/configserver/util/Infrastructure.java
backend/src/test/java/io/debezium/configserver/util/MultipleKafkaConnectClustersTestProfile.java
docker-compose.yml
oc-demo/05-ui.yaml

closes https://issues.redhat.com/browse/DBZ-4066

DBZ-4066 Change Debezium UI configurations property names and update to latest UI config changes

---

.github/workflows/backend-testing.yml
backend/src/test/java/io/debezium/configserver/ListPostgresConnectorIT.java

https://issues.redhat.com/browse/DBZ-3872

DBZ-3872 Disable connector start retries

---

backend/pom.xml

https://issues.redhat.com/browse/DBZ-4460

DBZ-4460 Update UI backend to fetch generated schema from connector archives

---

ui/README.md

Updates the README to show the latest node and npm version requirments

DBZ-4630 Update the node and npm version requirements

---

.github/workflows/octocat-commits-check.yml
.github/workflows/sanity-check.yml

https://issues.redhat.com/browse/DBZ-3143

DBZ-3143 Add Octocat and Commit Message Checks

---

ui/pom.xml

https://issues.redhat.com/browse/DBZ-4622

DBZ-4622:Stop generating package-lock.json when run mvn clean package

---

backend/src/main/java/io/debezium/configserver/rest/ConnectorResource.java
backend/src/main/java/io/debezium/configserver/rest/ConnectorURIs.java
backend/src/main/java/io/debezium/configserver/rest/client/KafkaConnectClient.java
backend/src/test/java/io/debezium/configserver/ConnectorResourceIT.java

Addition of the backend service to support fetching the connector config after the connector has been created.

DBZ-4627 Add backend service to get connector config

---

backend/src/main/java/io/debezium/configserver/service/sqlserver/SqlServerConnectorIntegrator.java

https://github.com/debezium/docker-images/runs/5734598722?check_suite_focus=true

DBZ-4920 Sync method name with core

---

ui/packages/ui/__tests__/shared/Utils.test.tsx
ui/packages/ui/src/app/components/connectorStepHelpers/PropertiesStepsComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/PropertiesStep.tsx
ui/packages/ui/src/app/pages/createConnector/federatedModule/Properties.tsx
ui/packages/ui/src/app/shared/Utils.ts

Issue https://issues.redhat.com/browse/DBZ-4619

DBZ-4981: fix: Add the advance ssl catagory in property step.

---

ui/package-lock.json

https://issues.redhat.com/browse/DBZ-4881

DBZ-4881: fix(deps): Update dependencies to fix Dependabot alerts

---

ui/package-lock.json
ui/package.json

https://issues.redhat.com/browse/DBZ-4881

DBZ-4881: fix(deps): Update frontend-components-config

---

ui/packages/ui/src/app/components/connectorStepHelpers/RuntimeOptionsComponent.tsx
ui/packages/ui/src/app/components/formHelpers/FormInputComponent.css
ui/packages/ui/src/app/components/formHelpers/FormInputComponent.tsx
ui/packages/ui/src/app/components/topicCreationHelpers/TopicDefaults.tsx
ui/packages/ui/src/app/components/topicCreationHelpers/TopicGroupConfig.tsx
ui/packages/ui/src/app/components/transformHelpers/TransformConfig.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/PropertiesStep.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/RuntimeOptionsStep.tsx

https://issues.redhat.com/browse/DBZ-5067

DBZ-5067: fix: Debezium MCS Error when changing Postgres port

---

backend/pom.xml
backend/src/test/java/io/debezium/configserver/CreateAndDeleteSqlSeverConnectorIT.java
backend/src/test/java/io/debezium/configserver/NativeCreateAndDeleteSqlServerConnectorIT.java
backend/src/test/java/io/debezium/configserver/ValidateSqlServerFiltersIT.java
backend/src/test/java/io/debezium/configserver/ValidateSqlSeverDatabasesIT.java
backend/src/test/java/io/debezium/configserver/util/Infrastructure.java
backend/src/test/java/io/debezium/configserver/util/SqlServerInfrastructureTestProfile.java
backend/src/test/java/io/debezium/configserver/util/SqlServerInfrastructureTestResourceLifecycleManager.java
backend/src/test/resources/initialize-sqlserver-database.sql

https://issues.redhat.com/browse/DBZ-4867

DBZ-4867 Add tests for SQL Server connector

---

ui/packages/ui/src/app/pages/connectors/ConnectorDrawer.tsx

https://issues.redhat.com/projects/DBZ/issues/DBZ-5378

DBZ-5378 Fix view connector config in non-first cluster

---

backend/src/main/java/io/debezium/configserver/service/mongodb/MongoDbConnectorIntegrator.java
backend/src/main/java/io/debezium/configserver/service/mysql/MySqlConnectorIntegrator.java
backend/src/main/java/io/debezium/configserver/service/postgres/PostgresConnectorIntegrator.java
backend/src/main/java/io/debezium/configserver/service/sqlserver/SqlServerConnectorIntegrator.java
backend/src/test/java/io/debezium/configserver/util/Infrastructure.java
pom.xml

https://issues.redhat.com/browse/DBZ-5317

DBZ-5317 Upgrade DBZ UI to 1.9.5.Final

---

backend/src/main/java/io/debezium/configserver/service/ConnectorIntegratorBase.java

https://issues.redhat.com/browse/DBZ-5229
This follows a similar principle as done in the schema generator in the core repository in PR https://github.com/debezium/debezium/pull/3829 by which we explicitly inject the Kafka-based connector fields into the configuration if the connector contains a `database.history` property as a part of its base configuration definition.
This approach doesn't support other storage modules, but it at least restores the broken functionality until a larger discussion can be had on how best to integrate these additional storage modules with the UI project and downstream components.

DBZ-5229 Restore Kafka-based database history options

---

ui/packages/services/src/baseService.ts
ui/packages/services/src/config/config.service.ts
ui/packages/services/src/config/config.type.ts
ui/packages/services/src/connector/connector.service.ts
ui/packages/services/src/globals/globals.service.ts
ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/PropertiesStep.tsx
ui/packages/ui/src/app/utils/FormatCosProperties.ts

Closes https://issues.redhat.com/browse/DBZ-4619

DBZ-4619: Move DBZ UI to new URLs and new JSON Schema

---

backend/src/main/java/io/debezium/configserver/service/sqlserver/SqlServerConnectorIntegrator.java

DBZ-5585 DBZ-5496 Classloader no longer needed; Azure SQL compatibility

---

ui/packages/ui/src/app/components/connectorStepHelpers/FilterExcludeFieldComponent.tsx
ui/packages/ui/src/app/components/connectorStepHelpers/FilterInputFieldComponent.tsx

closes https://issues.redhat.com/browse/DBZ-6174

DBZ-6174: Add the unique html name attibute to the filter fields

---

backend/src/test/java/io/debezium/configserver/util/Infrastructure.java
pom.xml

https://issues.redhat.com/browse/DBZ-6406

DBZ-6406 Update to Debezium 2.3.x

---

backend/pom.xml
backend/src/test/java/io/debezium/configserver/CreateAndDeleteMongoDbConnectorIT.java
backend/src/test/java/io/debezium/configserver/NativeCreateAndDeleteMongoDbConnectorIT.java
backend/src/test/java/io/debezium/configserver/ValidateMongoDbFiltersIT.java
backend/src/test/java/io/debezium/configserver/util/Infrastructure.java
backend/src/test/java/io/debezium/configserver/util/MongoDbInfrastructureTestResourceLifecycleManager.java

The few tests I tried worked on my MacOS machine. Somebody should try it on linux.
This PR supersedes ##700

DBZ-6363 Replacing MongoDbContainer with MongoDbReplicaSet and fixing mongodb visibility for other containers

---

ui/packages/ui/src/app/pages/createConnector/connectorSteps/ConnectorTypeStep.css

DBZ-6392: Fix the connector cards alignment

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx

Fixed the Back button on the Review page.

DBZ-5841: Fix back button on the review page.

---

.gitignore
backend/src/main/resources/application.properties

https://issues.redhat.com/browse/DBZ-6422

DBZ-6422 Fix CORS error due to Quarkus 3 upgrade

---

.github/workflows/end-to-end-testing-oracle.yml
.github/workflows/end-to-end-testing.yml
backend/src/main/java/io/debezium/configserver/rest/ConnectorResource.java
backend/src/test/java/io/debezium/configserver/ConnectorResourceIT.java

closes https://issues.redhat.com/browse/DBZ-5604

DBZ-5604 Remove old connector type endpoint

---

backend/pom.xml
backend/src/main/java/io/debezium/configserver/rest/ConnectorResource.java
backend/src/main/java/io/debezium/configserver/service/ConnectorIntegratorBase.java
backend/src/test/java/io/debezium/configserver/CreateAndDeleteMongoDbConnectorIT.java
backend/src/test/java/io/debezium/configserver/ValidateMongoDbFiltersIT.java
backend/src/test/java/io/debezium/configserver/util/Infrastructure.java
backend/src/test/java/io/debezium/configserver/util/MongoDbInfrastructureTestResourceLifecycleManager.java

closes https://issues.redhat.com/browse/DBZ-6426

DBZ-6426 Correctly ignore unsupported connectors, including unsupported Debezium connectors

---

backend/pom.xml
pom.xml

relates to #710 
see https://github.com/debezium/debezium-ui/pull/710#discussion_r1188619144
closes https://issues.redhat.com/browse/DBZ-6453

DBZ-6453 Use debezium-bom versions for shared dependencies

---

backend/src/test/java/io/debezium/configserver/util/Infrastructure.java

https://issues.redhat.com/browse/DBZ-6449

DBZ-6449 Use debezium/kafka image in the tests

---

.github/workflows/end-to-end-testing-oracle.yml
.github/workflows/end-to-end-testing.yml
backend/pom.xml
backend/src/main/java/io/debezium/configserver/service/mongodb/MongoDbConnectorIntegrator.java
backend/src/main/java/io/debezium/configserver/service/sqlserver/SqlServerConnectorIntegrator.java
backend/src/test/java/io/debezium/configserver/util/Infrastructure.java
backend/src/test/java/io/debezium/configserver/util/PropertiesReader.java
docker-compose-oracle.yml
docker-compose.yml
pom.xml

closes https://issues.redhat.com/browse/DBZ-6639

DBZ-6639 Use Debezium version from pom.xml properties for Testcontainers CI tests

---

ui/packages/ui/src/app/pages/connectors/ConnectorOverview.tsx

DBZ-5360: Update the millisecond value since last event to more readable time

---

ui/packages/ui/src/app/pages/connectors/ConnectorOverview.tsx

DBZ-6681: Update text value in case of no events

---

ui/packages/ui/src/app/pages/connectors/ConnectorTask.css

DBZ-5831: Provide outline for drawer component showing connector details

---

ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx
ui/packages/ui/src/app/pages/createConnector/connectorSteps/CustomPropertiesStep.tsx
ui/packages/ui/src/app/pages/editConnector/EditConnectorComponent.tsx

Fix: https://issues.redhat.com/browse/DBZ-6711

DBZ-6711: add only user modified prop in validation

---

backend/src/main/java/io/debezium/configserver/service/mongodb/MongoDbConnectorIntegrator.java

https://issues.redhat.com/browse/DBZ-6731

DBZ-6731 Align to blocking snapshot behavior

---

src/app/apis/connector/connector.service.ts
src/app/components/ConnectorStatusComponent.css
src/app/components/ConnectorStatusComponent.tsx
src/app/hooks/index.ts
src/app/hooks/useFetchApiMultiVariableApi.tsx
src/app/pages/connectorDetails/ConnectorDetails.css
src/app/pages/connectorDetails/ConnectorDetails.tsx
src/app/utils/connector.d.ts
src/app/utils/utilityFunctions.ts

DBZ-6757: Fixes to the connector metrics

---

Dockerfile
config.js
config.json
deployment/image/create-dbzui-config.sh
dev.Dockerfile

closes https://issues.redhat.com/browse/DBZ-7447

DBZ-7447 Add Debezium UI container image for production use based on nginx-alpine
